services:
  redisnode0:
    image: redis_mine
    command: redis-server redis.conf
  
  redisnode1:
    image: redis_mine
    command: redis-server redis.conf
  
  redisnode2:
    image: redis_mine
    command: redis-server redis.conf
  
  redisnode3:
    image: redis_mine
    command: redis-server redis.conf
  
  redisnode4:
    image: redis_mine
    command: redis-server redis.conf
  
  redisnode5:
    image: redis_mine
    command: redis-server redis.conf
  
  cluster_creator:
    image: redis:latest
    command: redis-cli --cluster create  redisnode0:9000  redisnode1:9000  redisnode2:9000  redisnode3:9000  redisnode4:9000  redisnode5:9000  --cluster-yes
    depends_on:
      - redisnode0
      - redisnode1
      - redisnode2
      - redisnode3
      - redisnode4
      - redisnode5

  nginx_redis:
    image: nginx_redis_mine
    depends_on:
      - redisnode0
      - redisnode1
      - redisnode2
      - redisnode3
      - redisnode4
      - redisnode5